addressBook/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace addressBook.Models
{
    public class User
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        [DataType(DataType.Date)]
            [DisplayFormat(DataFormatString =
            "{0:dd.MM.yyyy.}",ApplyFormatInEditMode =false)]
        public DateTime BirthDay { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }

        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
    }
}

addressBook/Controllers/PhoneNumbersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using addressBook.DAL;
using addressBook.Models;

namespace addressBook.Controllers
{
    public class PhoneNumbersController : Controller
    {
        private BookContext db = new BookContext();

        // GET: PhoneNumbers
        //public ActionResult Index()
        //{
        //    var phoneNumbers = db.PhoneNumbers.Include(p => p.User);
        //    return View(phoneNumbers.ToList());
        //}

        // GET: PhoneNumbers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhoneNumber phoneNumber = db.PhoneNumbers.Find(id);
            if (phoneNumber == null)
            {
                return HttpNotFound();
            }
            return View(phoneNumber);
        }

        // GET: PhoneNumbers/Create
        public ActionResult Create(int? UserID)
        {
            //ViewBag.UserID = new SelectList(db.Users, "UserID", "Name");
            SelectList selectList= new SelectList(db.Users, "UserID", "Name");
            if (UserID!=null)
                selectList.Where(s => Int32.Parse(s.Value) == UserID).First().Selected = true;
            ViewBag.UserID = selectList;

            return View();
        }

        // POST: PhoneNumbers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Number,Type,IsDefault,UserID")] PhoneNumber phoneNumber)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    phoneNumber.IsDefault = false;
                    db.PhoneNumbers.Add(phoneNumber);
                    db.SaveChanges();
                    return RedirectToAction("Edit", "Users", new { id = phoneNumber.UserID });
                }
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "Can't save changes. Try later.");
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", phoneNumber.UserID);
            return View(phoneNumber);
        }

        public ActionResult MakeDefault(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.PhoneNumbers.Find(id).User;
            try
            {
                IEnumerable<PhoneNumber> phoneNumbers = db.PhoneNumbers.Where(p => p.UserID == user.UserID);
                foreach (var p in phoneNumbers)
                {
                    if (p.PhoneNumberID != id)
                        p.IsDefault = false;
                    else
                        p.IsDefault = true;
                }
                db.SaveChanges();
            }
            catch(DataException)
            {
                ModelState.AddModelError("","Can't save changes. Try later");
            }

            return RedirectToAction("Edit", "Users", new { id = user.UserID });
        }

        // GET: PhoneNumbers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhoneNumber phoneNumber = db.PhoneNumbers.Find(id);
            if (phoneNumber == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", phoneNumber.UserID);
            return View(phoneNumber);
        }

        // POST: PhoneNumbers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhoneNumberID,Number,Type,IsDefault,UserID")] PhoneNumber phoneNumber)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(phoneNumber).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Edit", "Users", new { id = phoneNumber.UserID });
                }
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "Can't save changes. Try later.");
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", phoneNumber.UserID);
            return View(phoneNumber);
        }

        // GET: PhoneNumbers/Delete/5
        public ActionResult Delete(int? id,bool? deleteError=false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if(deleteError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Can't delete. Try again.";
            }
            PhoneNumber phoneNumber = db.PhoneNumbers.Find(id);
            if (phoneNumber == null)
            {
                return HttpNotFound();
            }
            return View(phoneNumber);
        }

        // POST: PhoneNumbers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhoneNumber phoneNumber = db.PhoneNumbers.Find(id);
            try
            {
                db.PhoneNumbers.Remove(phoneNumber);
                db.SaveChanges();
            }
            catch(DataException)
            {
                return RedirectToAction("Delete", new { id = id, deleteError = true });
            }
            return RedirectToAction("Edit","Users",new { id=phoneNumber.UserID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

addressBook/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using addressBook.DAL;
using addressBook.Models;

namespace addressBook.Controllers
{
    public class UsersController : Controller
    {
        private BookContext db = new BookContext();

        // GET: Users
        public ActionResult Index(string findInName,string findInSurname,string findInPhoneNumber)
        {
            var users = new List<User>();
            if (!String.IsNullOrEmpty(findInPhoneNumber))
            {
                ViewBag.isSearchedByNumber = true;
                var searchedNumber = findInPhoneNumber.ToString();
                var phoneNumbersMatch = db.PhoneNumbers.Where(
                                            p => p.Number.ToString().Contains(searchedNumber)).ToList();

                users.Clear();
                foreach (var p in phoneNumbersMatch)
                {
                    var user = new User();

                    user.UserID = p.UserID; user.Name = p.User.Name;
                    user.Surname = p.User.Surname; user.BirthDay = p.User.BirthDay;
                    user.Address = p.User.Address; user.Email = p.User.Email;
                    user.PhoneNumbers = new List<PhoneNumber>();

                    user.PhoneNumbers.Add(p);
                    users.Add(user);
                }
            }
            else
            {
                users = db.Users.ToList();
                ViewBag.isSearchedByNumber = false;

                if (!String.IsNullOrEmpty(findInName))
                    users = users.Where(u => u.Name.IndexOf(findInName,StringComparison.OrdinalIgnoreCase)>=0).ToList();
                if (!String.IsNullOrEmpty(findInSurname))
                    users = users.Where(u => u.Surname.IndexOf(findInSurname,StringComparison.OrdinalIgnoreCase)>=0).ToList();

                foreach (var user in users)
                {
                    var phoneNumber = new PhoneNumber();
                    phoneNumber = user.PhoneNumbers.Where(p => p.IsDefault).SingleOrDefault();
                    user.PhoneNumbers.Clear();
                    user.PhoneNumbers.Add(phoneNumber);
                }
            }
            return View(users);
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Surname,BirthDay,Address,Email")] User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "Can't save changes.Try later.");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,Name,Surname,BirthDay,Address,Email")] User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch(DataException)
            {
                ModelState.AddModelError("", "Can't save changes. Try later.");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id, bool? deleteError=false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if(deleteError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Can't delete.Try again";
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                User user = db.Users.Find(id);
                db.Users.Remove(user);
                db.SaveChanges();
            }
            catch(DataException)
            {
                return RedirectToAction("Delete", new { id = id, deleteError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

addressBook/Views/Users/Create.cshtml
@model addressBook.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

addressBook/Views/Users/Delete.cshtml
@model addressBook.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<p>@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

addressBook/Views/Users/Details.cshtml
@model addressBook.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

addressBook/Views/Users/Edit.cshtml
@model addressBook.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDay, new { htmlAttributes = new { @class = "form-control", @Value=Model.BirthDay.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.BirthDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br />
<a href="@Url.Action("Create", "PhoneNumbers", new { UserID=Model.UserID })">Add phone number</a><br /><br />

@if(Model.PhoneNumbers!=null)
{
    <table class="table">
        <tr>
            <th>Number</th>
            <th>Type</th>
            <th></th>
            <th></th>
        </tr>

        @foreach(var item in Model.PhoneNumbers)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Number)</td>
                <td>@Html.DisplayFor(modelItem => item.Type)</td>
                @if (!item.IsDefault)
                    {<td><a href="@Url.Action("MakeDefault", "PhoneNumbers", new { id = item.PhoneNumberID })">Make Default</a></td> }
                 else
                    { <td>Currently default</td>}

                <td>
                    <a href="@Url.Action("Edit", "PhoneNumbers",new { id=item.PhoneNumberID})">Edit</a> |
                    <a href="@Url.Action("Details", "PhoneNumbers",new { id=item.PhoneNumberID})">Details</a> |
                    <a href="@Url.Action("Delete", "PhoneNumbers",new { id=item.PhoneNumberID})">Delete</a>
                </td>
            </tr>
        }

    </table>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

addressBook/Views/Users/Index.cshtml
@model IEnumerable<addressBook.Models.User>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("findInName")
        <input type="submit">
    </p>
}

@using (Html.BeginForm())
{
    <p>
        Find by surname: @Html.TextBox("findInSurname")
        <input type="submit">
    </p>
}

@using (Html.BeginForm())
{
    <p>
    Find by phone number: @Html.TextBox("findInPhoneNumber")
    <input type="submit">
    </p>
}
<p> Click edit to edit user data and add or change user phone numbers</p>
<p>
    @Html.ActionLink("Create New User", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        @if (ViewBag.isSearchedByNumber) { <th> Found number</th>}
        else { <th> Default number</th>}
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumbers.ElementAt(0).Number)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserID }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserID })
        </td>
    </tr>
}

</table>